public enum Method {
    REGISTER,
    LOGIN,
    LOGOUT,
    INFORM,
    LIST, // all file names
    DETAILS,
    CHECK_ACTIVE_PEER_TO_PEER,
    CHECK_ACTIVE_TRACKER_TO_PEER,
    SIMPLE_DOWNLOAD,
    NOTIFY_SUCCESSFUL,
    NOTIFY_FAILED,
    SEEDER_SERVE,
    COLLABORATIVE_DOWNLOAD,
    SEEDER_SERVE_SUCCESSFUL

}
