public enum StatusCode {
    // Register from peer
    SUCCESSFUL_REGISTER,
    UNSUCCESSFUL_REGISTER,
    SUCCESSFUL_LOGOUT,
    UNSUCCESSFUL_LOGOUT,
    FILE_NOTFOUND,
    FILE_FOUND,
    PEER_ISACTIVE,
}
